ds041: ds041.cpp lib/mystack.o
	g++ -o ds041 ds041.cpp ./lib/mystack.o -I./lib

ds042: ds042.cpp  lib/mystack.o
	g++ -o ds042 ds042.cpp ./lib/mystack.o -I./lib

ds043: ds043.cpp lib/mystack.o
	g++ -o ds043 ds043.cpp ./lib/mystack.o -I./lib
