ds061: ds061.cpp lib/linkedlistQ.o
	g++ -o ds061 ds061.cpp ./lib/linkedlistQ.o -I./lib

ds062: ds062.cpp lib/linkedlistQ.o
	g++ -o ds062 ds061.cpp ./lib/linkedlistQ.o -I./lib

ds061: ds062.cpp lib/linkedlistQ.o
	g++ -o ds062 ds062.cpp ./lib/linkedlistQ.o -I./lib

linkedlistQ.o: lib/linkedlistQ.cpp lib/linkedlistQ.h
	g++ -c ./lib/linkedlistQ.cpp
